/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Control.*;

/**
 * 
 * @author Administrator
 */
public class View_Store extends javax.swing.JFrame {

	/**
	 * Creates new form View_Store
	 */
	ShopControl sc;
	int s;


	public View_Store(ShopControl sc) {
		initComponents();
		this.sc = sc;
		
	}
	
	public void setStoreMoney(String money)
	{
		jTextField1.setText(money);
	}
	/*public void chechStoreMoney()
	{
		if(vp.getChat().equals("돈이 부족합니다.")){
			JOptionPane.showConfirmDialog(this, "돈이 부족합니다","잔고확인",-1,0);
		}
		
	}*/

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	 private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "이동속도", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(369, 124));

        jButton10.setBackground(new java.awt.Color(60,179,113));
        jButton10.setText("바이크");
        jButton10.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton10.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton10.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("s2");
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255,182,193));
        jButton11.setText("발수트");
        jButton11.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton11.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton11.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("s3");
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(211,211,211));
        jButton12.setText("토르망토");
        jButton12.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton12.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton12.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("s4");
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(173,216,230));
        jButton13.setText("캡틴망토");
        jButton13.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton13.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton13.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("s1");
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "방어력", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(369, 124));

        jButton6.setBackground(new java.awt.Color(60,179,113));
        jButton6.setText("바지");
        jButton6.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton6.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton6.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("d2");
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255,182,193));
        jButton7.setText("몸통수트");
        jButton7.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton7.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton7.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("d3");
                jButton7ActionPerformed(evt);
            }
        });

        
        jButton8.setBackground(new java.awt.Color(211,211,211));
        jButton8.setText("갑옷");
        jButton8.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton8.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton8.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("d4");
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(173,216,230));
        jButton9.setText("쫄쫄이");
        jButton9.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton9.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton9.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("d1");
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "최대체력증가", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(369, 124));

        jButton14.setBackground(new java.awt.Color(60,179,113));
        jButton14.setText("벨트");
        jButton14.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton14.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton14.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("h2");
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255,182,193));
        jButton15.setText("머리수트");
        jButton15.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton15.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton15.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("h3");
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(211,211,211));
        jButton16.setText("토르헬멧");
        jButton16.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton16.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton16.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("h4");
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(173,216,230));
        jButton17.setText("캡틴헬멧");
        jButton17.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton17.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton17.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("h1");
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "스킬아이템", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(369, 124));

        jButton18.setBackground(new java.awt.Color(60,179,113));
        jButton18.setText("분노");
        jButton18.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton18.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton18.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("k2");
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255,182,193));
        jButton19.setText("손수트");
        jButton19.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton19.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton19.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("k3");
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(211,211,211));
        jButton20.setText("망치");
        jButton20.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton20.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton20.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("k4");
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(173,216,230));
        jButton21.setText("방패");
        jButton21.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton21.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton21.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("k1");
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTextField1.setText("현재나의금액");

        jButton1.setBackground(new java.awt.Color(255,255,224));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0,0,0));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "공격력", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(255,182,193));
        jButton2.setText("원자로");
        jButton2.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton2.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton2.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("a3");
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(60,179,113));
        jButton3.setText("너클");
        jButton3.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton3.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton3.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("a2");
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(173,216,230));
        jButton4.setText("근육");
        jButton4.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton4.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton4.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("a1");
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(211,211,211));
        jButton5.setText("큐브");
        jButton5.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton5.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton5.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("a4");
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "포션", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(369, 124));

        jButton22.setText("MP");
        jButton22.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton22.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton22.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("p2");
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("HP");
        jButton23.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton23.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton23.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("p1");
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("DF");
        jButton24.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton24.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton24.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("p4");
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("DM");
        jButton25.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton25.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton25.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("p3");
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("SP");
        jButton26.setMaximumSize(new java.awt.Dimension(81, 81));
        jButton26.setMinimumSize(new java.awt.Dimension(81, 81));
        jButton26.setPreferredSize(new java.awt.Dimension(81, 81));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	sc.setId("p5");
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton22, jButton23, jButton24, jButton25, jButton26});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4, jPanel5, jPanel6, jPanel7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4, jPanel5, jPanel6, jPanel7});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 10, 805, 469);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/배경4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 490);

        pack();
    }// </editor-fold>        
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("공격력 증가  가격 = 150(+lv = +60)", "토르_큐브");
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("공격력 증가  가격 = 150(+lv = +60)", "캡틴_근육");
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("공격력 증가  가격 = 150(+lv = +60)", "헐크_너클");
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("공격력 증가  가격 = 150(+lv = +60)", "아이언맨_원자로");
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("이동속도 증가  가격 = 150원(+lv = +50)", "아이언맨_발수트");
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("이동속도 증가  가격 = 150원(+lv = +50)", "헐크_바이크");
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("이동속도 증가  가격 = 150원(+lv = +50)", "캡틴_망토");
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("이동속도 증가  가격 = 150원(+lv = +50)", "토르_망토");
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("방어력 증가  가격 = 130원(+lv = +30)", "아이언맨_몸통수트");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("방어력 증가  가격 = 130원(+lv = +30)", "헐크_바지");
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("방어력 증가  가격 = 130원(+lv = +30)", "캡틴_쫄쫄이");

	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("방어력 증가  가격 = 130원(+lv = +30)", "토르_갑옷");

	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("최대체력 증가  가격 = 170원(+lv = +70)", "아이언맨_머리수트");
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("최대체력 증가  가격 = 170원(+lv = +70)", "헐크_벨트");
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("최대체력 증가  가격 = 170원(+lv = +70)", "캡틴_헬멧");
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("최대체력 증가  가격 = 170원(+lv = +70)", "토르_헬멧");
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("원거리 스킬  가격 = 200원(+lv = +70)", "아이언맨_손수트");
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("변신 스킬  가격 = 200원(+lv = +70)", "헐크_분노");
	}

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("원거리 스킬  가격 = 200원(+lv = +70)", "캡틴_방패");
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog("원거리 스킬  가격 = 200원(+lv = +70)", "토르_망치");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		ViewControl.s = null;
		sc.setId(null);
		sc.setLv(0);
		this.setVisible(false);
	}

	private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog2("마나 10회복(2개)  가격 = 30", "MP");
	}

	private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog2("체력 10회복(2개)  가격 = 30", "HP");
	}

	private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog2("방어력 3증가  가격 = 100", "DF");
	}

	private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog2("공격력 3증가  가격 = 100", "DM");
	}

	private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {
		getDialog2("이동속도 1증가  가격 = 100", "SP");
	}

	private void getDialog(String itemText, String itemTitle) {
		jComboBox = new javax.swing.JComboBox();
		jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"레벨", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
		jComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxActionPerformed(evt);
			}
		});

		Object[] options = { jComboBox, "구매하기", "취소" };
		int optionChosen = JOptionPane.showOptionDialog(this, itemText,
				itemTitle, WIDTH, -1, null, options, rootPane);

		if (optionChosen == 1) {
			
			ViewControl.s = sc.getId() + "(" + sc.getLv() + ") 구매하기";
			System.out.println("구매하기");
			System.out.println(sc.getId());
			System.out.println(sc.getLv());
			sc.buyItem();
			
			
			
		} else if (optionChosen == 2) {
			ViewControl.s = "취소하기";
			System.out.println("취소하기");
			sc.setId(null);
			sc.setLv(0);
		}
	}

	private void getDialog2(String itemText, String itemTitle) {

		Object[] options = { "구매하기", "취소" };
		int optionChosen = JOptionPane.showOptionDialog(this, itemText,
				itemTitle, WIDTH, -1, null, options, rootPane);

		if (optionChosen == 0) {
			ViewControl.s = sc.getId() + "구매하기";
			System.out.println("구매하기");
			System.out.println(sc.getId());
			System.out.println(sc.getLv());
			sc.buyItem();
		
		} else if (optionChosen == 1) {
			ViewControl.s = "취소하기";
			System.out.println("취소하기");
			sc.setId(null);
		}
	}

	private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {

		String temp = (String) this.jComboBox.getSelectedItem();

		if (temp.equals("레벨")) {
			sc.setCheckLv(false);
		} else {
			sc.setLv(Integer.parseInt(temp));
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(View_Store.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(View_Store.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(View_Store.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(View_Store.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// new View_Store().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JComboBox jComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
	// End of variables declaration
}
